version: "3.8"

services:
  sales:
    image: registry.jscorp.uz/botmother-sales:latest
    ports:
      - mode: ingress
        target: 3000
        published: ${PORT:?enviromentda PORT topilmadi}
        protocol: tcp
    networks:
      - botmother
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
        delay: 10s
        max_failure_ratio: 0.2
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:3000/uz/auth/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  botmother:
    driver: overlay
    attachable: true
    external: true

